name: Simple CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
  deploy:
    name: deploy 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create SSH Key File
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to Remote Server
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'

            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

            docker stop my-app || true
            docker rm my-app || true

            docker run -d --name my-app -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

          EOF
